set(CMAKE_SYSTEM_NAME quark)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(QUARK_TOOLCHAIN_BIN "$ENV{HOME}/opt/cross/bin")
set(CMAKE_SYSROOT "$ENV{HOME}/opt/quark-sysroot")

set(CMAKE_C_COMPILER   ${QUARK_TOOLCHAIN_BIN}/x86_64-quark-gcc)
set(CMAKE_CXX_COMPILER ${QUARK_TOOLCHAIN_BIN}/x86_64-quark-g++)
set(CMAKE_ASM_NASM_COMPILER nasm)

set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)